datasources:
  default:
    url: jdbc:oracle:thin:@//localhost:1521/FREEPDB1
    driverClassName: oracle.jdbc.OracleDriver
    username: AuthService
    password: AuthServicePassword
jpa:
  default:
    enabled: true
    entity-scan:
      packages: com.ethan.Entities
micronaut:
  application:
    name: authService
    version: 0.1
    security:
      enabled: true
      token:
        jwt:
          signatures:
            secret:
              generator:
                secret: MockTokenSecret
        endpoints:
          login:
            enabled: true
            path: /auth/login


flyway:
  datasources:
    default:
      url: jdbc:oracle:thin:@//localhost:1521/FREEPDB1
      username: AuthService
      password: AuthServicePassword
      baseline-on-migrate: true

  oracle:
    sysdba: true