CREATE TABLE users (
                       user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR2(100) NOT NULL,
                       password_hash VARCHAR2(255) NOT NULL
);